version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - aws cloudformation package --template-file template.yml --s3-bucket chatbotprojectbucket --output-template-file outputTemplate.yml
artifacts:
    type: zip
    files:
        - template.yaml
        - outputTemplate.yaml

