AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions.
Resources:
  selectFuntion:
    Type: AWS::Serverless::Function
    Properties:
      Handler: selectFuntion.handler
      Runtime: nodejs10.x
      AutoPublishAlias: live
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource: '*'
      DeploymentPreference:
        Type: Linear10PercentEvery1Minute
        Hooks:
          PreTraffic:
            Ref: beforeAllowTraffic
          PostTraffic:
            Ref: afterAllowTraffic
      CodeUri: s3://chatbotprojectbucket/1ebaeb01a4a5bbd44ba1cdb363d76110
  beforeAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: beforeAllowTraffic.handler
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Resource:
            Fn::Sub: arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource:
            Ref: selectFuntion.Version
      Runtime: nodejs10.x
      FunctionName: CodeDeployHook_beforeAllowTraffic
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Environment:
        Variables:
          NewVersion:
            Ref: selectFuntion.Version
      CodeUri: s3://chatbotprojectbucket/1ebaeb01a4a5bbd44ba1cdb363d76110
  afterAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: afterAllowTraffic.handler
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - codedeploy:PutLifecycleEventHookExecutionStatus
          Resource:
            Fn::Sub: arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - lambda:InvokeFunction
          Resource:
            Ref: selectFuntion.Version
      Runtime: nodejs10.x
      FunctionName: CodeDeployHook_afterAllowTraffic
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Environment:
        Variables:
          NewVersion:
            Ref: selectFuntion.Version
      CodeUri: s3://chatbotprojectbucket/1ebaeb01a4a5bbd44ba1cdb363d76110
